Repository CommunityToolkit/Maui, pull requests merged in 2022-11, with the labels that each got.

#720 For Source Generators, Ensure `GetGenericTypeConstraintsAsString` Includes Namespace for Type
  src/CommunityToolkit.Maui.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
  src/CommunityToolkit.Maui.UnitTests/Extensions/TextColorToTests.cs
Labels: hacktoberfest-accepted

#673 StateContainer
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Layouts/StateContainerPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Layouts/StateContainerPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Layouts/UniformItemsLayoutPage.xaml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/LayoutsGalleryViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/StateContainerViewModel.cs
  src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
  src/CommunityToolkit.Maui.UnitTests/Layouts/StateContainerTests.cs
  src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainer.shared.cs
  src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainerController.shared.cs
  src/CommunityToolkit.Maui/Layouts/StateContainer/StateView.shared.cs
Labels: approved, documentation approved, hacktoberfest-accepted

#635 Add DockLayout (docks views to the edges of the layout container)
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Layouts/DockLayoutPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Layouts/DockLayoutPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/DockLayoutViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/LayoutsGalleryViewModel.cs
  src/CommunityToolkit.Maui.Core/Interfaces/IDockLayout.shared.cs
  src/CommunityToolkit.Maui.Core/Interfaces/IUniformItemsLayout.shared.cs
  src/CommunityToolkit.Maui.Core/Layouts/DockLayoutManager.shared.cs
  src/CommunityToolkit.Maui.Core/Layouts/UniformItemsLayoutManager.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/AlertViewVisualOptions.macios.cs
  src/CommunityToolkit.Maui.Core/Primitives/DockPosition.shared.cs
  src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
  src/CommunityToolkit.Maui.UnitTests/Layouts/DockLayoutTests.cs
  src/CommunityToolkit.Maui.UnitTests/Layouts/UniformItemsLayoutTests.cs
  src/CommunityToolkit.Maui/Layouts/DockLayout.shared.cs
  src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainer.shared.cs
  src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainerController.shared.cs
  src/CommunityToolkit.Maui/Layouts/UniformItemsLayout.shared.cs
Labels: hacktoberfest-accepted

#478 Expander
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPageCS.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ExpanderViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
  src/CommunityToolkit.Maui.Core/Interfaces/IExpander.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/ExpandDirection.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/ExpandedChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Views/Expander/ExpandedChangedEventArgsTests.cs
  src/CommunityToolkit.Maui.UnitTests/Views/Expander/ExpanderTests.cs
  src/CommunityToolkit.Maui/Views/Expander/Expander.shared.cs
Labels: pending documentation, hacktoberfest-accepted

#692 Implements tizen platform
  Directory.Build.props
  azure-pipelines.yml
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/Platforms/Tizen/Main.cs
  samples/CommunityToolkit.Maui.Sample/Platforms/Tizen/tizen-manifest.xml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ButtonPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/CsharpBindingPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/MultipleButtonPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/NoOutsideTapDismissPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/OpenedEventSimplePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ReturnResultPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/SimplePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ToggleSizePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/XamlBindingPopup.xaml
  src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
  src/CommunityToolkit.Maui.Core/Handlers/DrawingView/DrawingViewHandler.shared.cs
  src/CommunityToolkit.Maui.Core/Handlers/Popup/PopupHandler.tizen.cs
  src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.tizen.cs
  src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.tizen.cs
  src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.tizen.cs
  src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.tizen.cs
  src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.tizen.cs
  src/CommunityToolkit.Maui/Alerts/Toast/Toast.tizen.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/SelectAllText/SelectAllTextBehavior.tizen.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/StatusBar/StatusBarBehavior.shared.cs
  src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
Labels: hacktoberfest-accepted

#681 Prepare to .NET 7 release
  azure-pipelines.yml
  global.json
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/Pages/Alerts/SnackbarPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewRatingPage.xaml
  src/CommunityToolkit.Maui.Analyzers.CodeFixes/CommunityToolkit.Maui.Analyzers.CodeFixes.csproj
  src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
  src/CommunityToolkit.Maui.Analyzers/CommunityToolkit.Maui.Analyzers.csproj
  src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
  src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.ios.cs
  src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.net.cs
  src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
  src/CommunityToolkit.Maui.Core/Views/PaddedButton.macios.cs
  src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs
  src/CommunityToolkit.Maui.Core/Views/Toast/PlatformToast.macios.cs
  src/CommunityToolkit.Maui.SourceGenerators/CommunityToolkit.Maui.SourceGenerators.csproj
  src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
  src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.android.cs
  src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
  src/CommunityToolkit.Maui/ImageSources/GravatarImageSource.shared.cs
Labels: hacktoberfest-accepted
