Repository CommunityToolkit/Maui, pull requests merged in 2022-07, with the labels that each got.

#456 Icon tint color behavior
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Resources/Images/shield.png
  samples/CommunityToolkit.Maui.Sample/Resources/Styles/Styles.xaml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/BehaviorsGalleryViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/IconTintColorBehaviorViewModel.cs
  src/CommunityToolkit.Maui.UnitTests/Behaviors/IconTintColorBehavior_Tests.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.ios.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs
Labels: pending documentation, approved

#494 IServiceCollectionExtensions
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/CsharpBindingPopupViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/XamlBindingPopupViewModel.cs
  src/CommunityToolkit.Maui.UnitTests/Extensions/ServiceCollectionExtensions_Tests.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockPage.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockPageRouteFactory.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockPageViewModel.cs
  src/CommunityToolkit.Maui/Extensions/ServiceCollectionExtensions.shared.cs
Labels: approved, documentation approved

#481 104 avatar view
  azure-pipelines.yml
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Models/AvatarModel.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewBindablePropertiesPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewBindablePropertiesPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewBordersPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewBordersPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewColorsPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewColorsPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewDayOfWeekPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewDayOfWeekPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewGesturesPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewGesturesPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewImagesPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewImagesPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewKeyboardPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewKeyboardPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewRatingPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewRatingPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewShadowsPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewShadowsPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewShapesPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewShapesPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewSizesPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewSizesPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/MultiplePopupPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/MultiplePopupPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupAnchorPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupAnchorPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupPositionPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupPositionPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Resources/Images/avatar_icon.png
  samples/CommunityToolkit.Maui.Sample/ViewModels/Base/BaseGalleryViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewBindablePropertiesViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewBordersViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewColorsViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewDayOfWeekViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewGesturesPage.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewImagesViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewKeyboardViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewRatingViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewShadowsViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewShapesViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/AvatarView/AvatarViewSizesViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/CsharpBindingPopupViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/MultiplePopupViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/PopupAnchorViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/PopupPositionViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/XamlBindingPopupViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
  src/CommunityToolkit.Maui.Core/Interfaces/IAvatarView.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/Defaults/AvatarViewDefaults.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/FontElementHandlerStub.cs
  src/CommunityToolkit.Maui.UnitTests/Views/AvatarView/AvatarViewTests.cs
  src/CommunityToolkit.Maui/Views/AvatarView.shared.cs
Labels: approved
