Repository CommunityToolkit/Maui, pull requests merged in 2023-11, with the labels that each got.

#1485 Change the display method of Popup Overlay on Windows
  src/CommunityToolkit.Maui.Core/Handlers/Popup/PopUpHandler.windows.cs
  src/CommunityToolkit.Maui.Core/Views/Popup/PopupOverlay.windows.cs
Labels: needs discussion

#1367 .NET 8
  .github/dependabot.yml
  Directory.Build.props
  azure-pipelines.yml
  global.json
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/Converters/SecondsToStringConverter.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Alerts/SnackbarPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/ImageSources/GravatarImageSourcePage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/BasicMapsPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/MapsPinsPage.xaml
  samples/CommunityToolkit.Maui.Sample/Resources/Images/splash.svg
  samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/CharactersValidationBehaviorViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/EnumToIntConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ItemTappedEventArgsConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ListToStringConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/SelectedItemEventArgsConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/ImageSources/GravatarImageSourceViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/CustomSizeAndPositionPopupViewModel.cs
  src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
  src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
  src/CommunityToolkit.Maui.Core/Interfaces/IDrawingView.shared.cs
  src/CommunityToolkit.Maui.Core/Layouts/UniformItemsLayoutManager.shared.cs
  src/CommunityToolkit.Maui.Core/Platform/KeyboardExtensions/KeyboardExtensions.shared.cs
  src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
  src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.android.cs
  src/CommunityToolkit.Maui.Maps/CommunityToolkit.Maui.Maps.csproj
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/MediaElement.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Behaviors/ProgressBarAnimationBehaviorTests.cs
  src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
  src/CommunityToolkit.Maui.UnitTests/Converters/CompareConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/MultiConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/SelectedItemEventArgsConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/StringToListConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/TextCaseConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/TimeSpanToSecondsConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Extensions/ColorConversionExtensionsTests.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockValueConverter.cs
  src/CommunityToolkit.Maui.UnitTests/Views/DrawingView/DrawingViewTests.cs
  src/CommunityToolkit.Maui.UnitTests/Views/MediaElement/MediaElementTests.cs
  src/CommunityToolkit.Maui.sln
  src/CommunityToolkit.Maui/Behaviors/EventToCommandBehavior.shared.cs
  src/CommunityToolkit.Maui/Behaviors/EventToCommandBehaviorGeneric.shared.cs
  src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
  src/CommunityToolkit.Maui/Converters/CompareConverter.shared.cs
  src/CommunityToolkit.Maui/Converters/ICommunityToolkitValueConverter.shared.cs
  src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MathExpression.shared.cs
  src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
  src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
Labels: breaking change

#1547 Remove SkiaSharp.Views Dependency
  src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
Labels: do not merge

#1543 Fix HLS CTD on Windows
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: 📽️ MediaElement

#1568 Fix Media Element crash in IOS with Sample app
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
Labels: 📽️ MediaElement
