Repository CommunityToolkit/Maui, pull requests merged in 2023-10, with the labels that each got.

#1351 Add Resources and Style to Popup
  .github/PULL_REQUEST_TEMPLATE.md
  samples/CommunityToolkit.Maui.Sample/App.xaml
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/StylePopupPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/StylePopupPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/StylePopupViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ApplyToDerivedTypesPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ApplyToDerivedTypesPopup.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/DynamicStyleInheritancePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/DynamicStyleInheritancePopup.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/DynamicStylePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/DynamicStylePopup.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ExplicitStylePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ExplicitStylePopup.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ImplicitStylePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/ImplicitStylePopup.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/StyleClassPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/StyleClassPopup.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/StyleInheritancePopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/StyleInheritancePopup.xaml.cs
  src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
Labels: approved

#1442 Add forced update of ScrollView on iOS
  src/CommunityToolkit.Maui/Views/Expander/Expander.shared.cs
Labels: hacktoberfest-accepted

#1369 Remove restriction for displaying Popup on iOS
  src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
Labels: hacktoberfest-accepted

#1440 Add drawing started, cancelled, and on-drawing commands
  samples/CommunityToolkit.Maui.Sample/Pages/Views/DrawingViewPage.xaml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/DrawingViewViewModel.cs
  src/CommunityToolkit.Maui.Core/Handlers/DrawingView/DrawingViewHandler.shared.cs
  src/CommunityToolkit.Maui.Core/Interfaces/IDrawingView.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/DrawingLineCompletedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/DrawingLineStartedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/MauiDrawingStartedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/MauiOnDrawingEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/PointDrawnEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockDrawingViewHandler.cs
  src/CommunityToolkit.Maui.UnitTests/Views/DrawingView/DrawingViewTests.cs
  src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
Labels: approved, hacktoberfest-accepted
