Repository CommunityToolkit/Maui, pull requests merged in 2023-09, with the labels that each got.

#1388 [MediaElement] Pre-initialize the Player Volume and Muted Properties
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
Labels: 📽️ MediaElement

#1341 Fixed Path behavior of FileSaver and FolderPicker on Android + Permission check on Android 13
  src/CommunityToolkit.Maui.Core/Essentials/AndroidStorageConstants.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaver.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/IFileSaver.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPicker.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/IFolderPicker.shared.cs
  src/CommunityToolkit.Maui.Core/Extensions/AndroidPathExtensions.android.cs
Labels: needs discussion

#1315 Allow change position after MediaEnded event
  src/CommunityToolkit.Maui.MediaElement/MediaElement.shared.cs
Labels: needs discussion

#1382 Speech Recognition v2 - StartListening/StopListening
  Directory.Build.props
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/SpeechToTextPage.xaml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ByteArrayToImageSourceConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/Events/SpeechToTextRecognitionResultCompletedEventArgs.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/Events/SpeechToTextRecognitionResultUpdatedEventArgs.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/Events/SpeechToTextStateChangedEventArgs.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/ISpeechToText.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SharedSpeechToTextImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToText.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.ios.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.macos.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.net.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.tizen.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.windows.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextState.shared.cs
  src/CommunityToolkit.Maui.Core/Views/SemanticOrderView/MauiSemanticOrderView.android.cs
  src/CommunityToolkit.Maui.UnitTests/Essentials/SpeechToTextTests.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/SpeechToTextImplementationMock.cs
  src/CommunityToolkit.Maui/Alerts/Toast/Toast.windows.cs
Labels: pending documentation
