Repository CommunityToolkit/Maui, pull requests merged in 2023-05, with the labels that each got.

#1121 Promote `MediaManager.PlatformSeek()` from `void` to `ValueTask`
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.android.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.tizen.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.tizen.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: help wanted, stale

#1015 Perform MediaElement Seek on main thread for WinUI
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/ISpeechToText.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SharedSpeechToTextImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToText.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.shared.cs
  src/CommunityToolkit.Maui.Core/Platform/KeyboardExtensions/KeyboardExtensions.macos.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.android.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.tizen.cs
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.tizen.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: 📽️ MediaElement

#604 [Maps] Add Windows map handler based on Webview
  azure-pipelines.yml
  samples/CommunityToolkit.Maui.Sample.sln
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/BasicMapsPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/BasicMapsPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/MapsPinsPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/MapsPinsPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Maps/MapsPinsViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Maps/MapsViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
  src/CommunityToolkit.Maui.Maps/AppHostBuilderExtensions.shared.cs
  src/CommunityToolkit.Maui.Maps/CommunityToolkit.Maui.Maps.csproj
  src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs
  src/CommunityToolkit.Maui.Maps/ReadMe.txt
  src/CommunityToolkit.Maui.sln
Labels: help wanted, hacktoberfest-accepted
