Repository CommunityToolkit/Maui, pull requests merged in 2023-01, with the labels that each got.

#699 Create `IFileSaver.SaveAsync()` and `IFolderPicker.PickAsync()`
  Directory.Build.props
  samples/CommunityToolkit.Maui.Sample.sln
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/EssentialsGalleryPage.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FileSaverPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FileSaverPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FolderPickerPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FolderPickerPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Platforms/Android/AndroidManifest.xml
  samples/CommunityToolkit.Maui.Sample/Platforms/Tizen/tizen-manifest.xml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/EssentialsGalleryViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FileSaverViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FolderPickerViewModel.cs
  src/CommunityToolkit.Maui.Analyzers/UseCommunityToolkitInitializationAnalyzer.cs
  src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
  src/CommunityToolkit.Maui.Core/Essentials/AndroidRequestCode.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileFolderDialog.tizen.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileFolderDialogLocalization.tizen.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaveException.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaver.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.net.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.tizen.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.windows.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/IFileSaver.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPicker.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerException.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.net.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.tizen.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.windows.cs
  src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/IFolderPicker.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/Folder.shared.cs
  src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
  src/CommunityToolkit.Maui.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
  src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
  src/CommunityToolkit.Maui.UnitTests/Essentials/FileSaverTests.cs
  src/CommunityToolkit.Maui.UnitTests/Essentials/FolderPickerTests.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/FileSaverImplementationMock.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/FolderPickerImplementationMock.cs
  src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
Labels: documentation approved, hacktoberfest-accepted

#916 Update build pipeline to enable separate MediaElement release
  azure-pipelines.yml
Labels: ♻ housekeeping

#930 Update Xcode version in build pipeline
  azure-pipelines.yml
Labels: ♻ housekeeping

#928 Various MediaElement fixes
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: 📽️ MediaElement
