Repository CommunityToolkit/Maui, pull requests merged in 2024-06, with the labels that each got.

#1782 Lock Screen Controls and Metadata Support for Windows, Android, IOS and Mac Catalyst
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Platforms/Android/AndroidManifest.xml
  samples/CommunityToolkit.Maui.Sample/Platforms/MacCatalyst/Info.plist
  samples/CommunityToolkit.Maui.Sample/Platforms/iOS/Info.plist
  src/CommunityToolkit.Maui.MediaElement/AppBuilderExtensions.shared.cs
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/Converters/FileMediaSourceConverter.cs
  src/CommunityToolkit.Maui.MediaElement/Interfaces/IMediaElement.cs
  src/CommunityToolkit.Maui.MediaElement/MediaElement.shared.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/AndroidMediaPermissions.android.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: approved, documentation approved, needs discussion

#1944 Don't copy Core & main package to artifacts for Camera package build
  azure-pipelines.yml
Labels: ♻ housekeeping

#1870 fixed sample application crashed with MediaElement for Windows
  Directory.Build.props
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
  src/CommunityToolkit.Maui.UnitTests/BaseHandlerTest.cs
  src/CommunityToolkit.Maui.UnitTests/BaseTest.cs
  src/CommunityToolkit.Maui.UnitTests/Essentials/AppThemeTests.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockApplication.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockResourcesProvider.cs
  src/CommunityToolkit.Maui/Extensions/AppThemeResourceExtension.shared.cs
Labels: approved

#1955 Update Media Element to fix code compliance
  src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
Labels: breaking change

#1965 Prevent volume bar from popping up on Android
  src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs
Labels: 📽️ MediaElement
