Repository CommunityToolkit/Maui, pull requests merged in 2024-03, with the labels that each got.

#1692 Media Element Full Screen Support for Android and Windows
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Platforms/Android/MainActivity.cs
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/Extensions/PageExtensions.cs
  src/CommunityToolkit.Maui.MediaElement/Resources/fullscreen.svg
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
Labels: 📽️ MediaElement

#1740 FileSaver Progress
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FileSaverPage.xaml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FileSaverViewModel.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaver.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.net.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.shared.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.tizen.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.windows.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/IFileSaver.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Essentials/FileSaverTests.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/FileSaverImplementationMock.cs
Labels: pending documentation, approved

#1771 Not use UseMauiMaps
  src/CommunityToolkit.Maui.Maps/AppHostBuilderExtensions.shared.cs
Labels: 🗺️ Map

#1683 Fix an issue with Popup size and position on Android
  src/CommunityToolkit.Maui.Core/Handlers/Popup/PopUpHandler.android.cs
  src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs
  src/CommunityToolkit.Maui/PlatformConfiguration/AndroidSpecific/NavigationBar.Impl.android.cs
Labels: breaking change

#1673 Add TouchBehavior
  .editorconfig
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/TouchBehaviorPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/TouchBehaviorPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Essentials/SpeechToTextPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupPositionPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/ShowPopupInOnAppearingPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Resources/Images/button.png
  samples/CommunityToolkit.Maui.Sample/Resources/Images/button_pressed.png
  samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/BehaviorsGalleryViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/TouchBehaviorViewModel.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/XamlBindingPopup.xaml
  src/CommunityToolkit.Maui.Core/Handlers/Popup/PopUpHandler.windows.cs
  src/CommunityToolkit.Maui.Core/Primitives/Defaults/ImageTouchBehaviorDefaults.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/Defaults/TouchBehaviorDefaults.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/HoverState.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/HoverStateChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/HoverStatus.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/HoverStatusChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/LongPressCompletedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchCompletedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchInteractionStatus.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchInteractionStatusChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchState.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchStateChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchStatus.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/TouchStatusChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.shared.cs
  src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
  src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.windows.cs
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
  src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
  src/CommunityToolkit.Maui.UnitTests/Behaviors/ImageTouchBehaviorTests.cs
  src/CommunityToolkit.Maui.UnitTests/Behaviors/TouchBehaviorTests.cs
  src/CommunityToolkit.Maui.UnitTests/ImageSources/GravatarImageSource/GravatarImageSourceTests.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/ImageTouch/ImageTouchBehavior.android.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/ImageTouch/ImageTouchBehavior.macios.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/ImageTouch/ImageTouchBehavior.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/ImageTouch/ImageTouchBehavior.windows.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/SelectAllText/SelectAllTextBehavior.macios.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/StatusBar/StatusBarBehavior.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/GestureManager.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.android.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.macios.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.methods.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.windows.cs
  src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
  src/CommunityToolkit.Maui/Converters/CompareConverter.shared.cs
  src/CommunityToolkit.Maui/Extensions/SafeFireAndForgotExtensions.shared.cs
  src/CommunityToolkit.Maui/Extensions/VisualElementExtensions.cs
  src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
  src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs
Labels: pending documentation
