Repository CommunityToolkit/Maui, pull requests merged in 2024-04, with the labels that each got.

#1767 Fixes Snackbar and Toast on iOS release builds
  src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
Labels: needs discussion

#1839 Replace `FrozenSet` with `IReadOnlyList`
  samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/CharactersValidationBehaviorViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/EnumToIntConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ItemTappedEventArgsConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ListToStringConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/SelectedItemEventArgsConverterViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/ImageSources/GravatarImageSourceViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/CustomSizeAndPositionPopupViewModel.cs
  src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
  src/CommunityToolkit.Maui.UnitTests/Behaviors/ProgressBarAnimationBehaviorTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/MultiConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/SelectedItemEventArgsConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/StringToListConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/TextCaseConverterTests.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/TimeSpanToSecondsConverterTests.cs
  src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MathExpression.shared.cs
Labels: breaking change

#1841 Improve the usage experience with CompareConverter in XAML
  samples/CommunityToolkit.Maui.Sample/Converters/CompareDoubleToColorConverter.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Converters/CompareConverterPage.xaml
  src/CommunityToolkit.Maui/Converters/CompareConverter.shared.cs
Labels: pending documentation, approved, breaking change

#1814 Fix Media Element Android Layout
  samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml
  samples/CommunityToolkit.Maui.Sample/Platforms/Android/MainActivity.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
Labels: pending documentation, approved
