Repository CommunityToolkit/Maui, pull requests merged in 2024-10, with the labels that each got.

#2238 Fix Windows Autoplay bug
  src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: 📽️ MediaElement

#2277 Fix FileSaver Progress
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs
  src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.shared.cs
Labels: hacktoberfest-accepted

#1688 Implement the ability to Close a popup
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/UpdatingPopupViewModel.cs
  samples/CommunityToolkit.Maui.Sample/Views/Popups/UpdatingPopup.xaml
  samples/CommunityToolkit.Maui.Sample/Views/Popups/UpdatingPopup.xaml.cs
  src/CommunityToolkit.Maui.Core/IPopupService.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockDispatcher.cs
  src/CommunityToolkit.Maui.UnitTests/Mocks/MockDispatcherProvider.cs
  src/CommunityToolkit.Maui.UnitTests/PopupServiceTests.cs
  src/CommunityToolkit.Maui/Popup/IPopupLifecycleController.cs
  src/CommunityToolkit.Maui/Popup/PopupLifecycleController.cs
  src/CommunityToolkit.Maui/PopupService.cs
Labels: help wanted, stale
