Repository CommunityToolkit/Maui, pull requests merged in 2025-01, with the labels that each got.

#2076 Update Media Element to use Media3
  samples/CommunityToolkit.Maui.Sample/Platforms/Android/AndroidManifest.xml
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/Primitives/AndroidMediaPermissions.android.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Primitives/PlayerViewChangedEventArgs.android.cs
  src/CommunityToolkit.Maui.MediaElement/Services/BoundServiceBinder.android.cs
  src/CommunityToolkit.Maui.MediaElement/Services/BoundServiceConnection.android.cs
  src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs
  src/CommunityToolkit.Maui.MediaElement/Services/SafeFireAndForgetExtensions.shared.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.tizen.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: 📽️ MediaElement, breaking change

#2182 Migrate to PEG parser. Introduce boolean operators and constants.
  samples/CommunityToolkit.Maui.Sample/Pages/Converters/MultiMathExpressionConverterPage.xaml
  src/CommunityToolkit.Maui.Core/Primitives/MathOperator.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Converters/MathExpressionConverterTests.cs
  src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MathExpression.shared.cs
  src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MathExpressionConverter.shared.cs
  src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MultiMathExpressionConverter.shared.cs
Labels: pending documentation, approved

#2091 Use GitHub Actions
  .github/workflows/SignClientFileList.txt
  .github/workflows/dotnet-build.yml
  azure-pipelines.yml
Labels: help wanted, stale

#2449 [CameraView] Android - Fix SetSurfaceProvider crash
  src/CommunityToolkit.Maui.Camera/CameraManager.android.cs
  src/CommunityToolkit.Maui.Camera/CommunityToolkit.Maui.Camera.csproj
Labels: needs discussion

#2329 Update MediaElement Transport Controls for Windows
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
  src/CommunityToolkit.Maui.MediaElement/Primitives/CustomTransportControls.windows.cs
  src/CommunityToolkit.Maui.MediaElement/ResourceDictionary.windows.xaml
  src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
  src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Labels: 📽️ MediaElement
