Repository CommunityToolkit/Maui, pull requests merged in 2025-06, with the labels that each got.

#2655 Refactor `CameraView.CaptureImage`, `CameraView.StartCameraPreview` and `CameraView.StopCameraPreview`
  samples/CommunityToolkit.Maui.Sample/Pages/Views/CameraView/CameraViewPage.xaml.cs
  src/CommunityToolkit.Maui.Camera/CameraInfo.shared.cs
  src/CommunityToolkit.Maui.Camera/CameraManager.android.cs
  src/CommunityToolkit.Maui.Camera/CameraManager.macios.cs
  src/CommunityToolkit.Maui.Camera/CameraManager.net.cs
  src/CommunityToolkit.Maui.Camera/CameraManager.shared.cs
  src/CommunityToolkit.Maui.Camera/CameraManager.tizen.cs
  src/CommunityToolkit.Maui.Camera/CameraManager.windows.cs
  src/CommunityToolkit.Maui.Camera/Extensions/CameraViewExtensions.android.cs
  src/CommunityToolkit.Maui.Camera/Extensions/CameraViewExtensions.macios.cs
  src/CommunityToolkit.Maui.Camera/Handlers/CameraViewHandler.shared.cs
  src/CommunityToolkit.Maui.Camera/Interfaces/IAsynchronouseHandler.cs
  src/CommunityToolkit.Maui.Camera/Interfaces/ICameraView.shared.cs
  src/CommunityToolkit.Maui.Camera/Primitives/CameraFlashMode.shared.cs
  src/CommunityToolkit.Maui.Camera/Primitives/CameraPosition.shared.cs
  src/CommunityToolkit.Maui.Camera/Primitives/CameraViewDefaults.shared.cs
  src/CommunityToolkit.Maui.Camera/Primitives/MediaCaptureFailedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Camera/Primitives/MediaCapturedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Camera/Providers/CameraProvider.android.cs
  src/CommunityToolkit.Maui.Camera/Providers/CameraProvider.macios.cs
  src/CommunityToolkit.Maui.Camera/Providers/CameraProvider.windows.cs
  src/CommunityToolkit.Maui.Camera/Views/CameraView.shared.cs
  src/CommunityToolkit.Maui.UnitTests/Views/CameraView/CameraViewTests.cs
Labels: pending documentation, approved, breaking change, Camera 📸

#2639 Update AppThemeResourceExtension to not use IProvideParentValues
  src/CommunityToolkit.Maui/Essentials/AppTheme/AppThemeObject.shared.cs
  src/CommunityToolkit.Maui/Extensions/AppThemeResourceExtension.shared.cs
Labels: area/extensions

#2715 Restrict AddPopup extensions to View to avoid ContentPage from being allowed
  src/CommunityToolkit.Maui/Extensions/ServiceCollectionExtensions.shared.cs
Labels: breaking change

#2705 Speech Recognition Windows Ensure unsubscribe from events on Stop Recording
  samples/CommunityToolkit.Maui.Sample/Platforms/Windows/Package.appxmanifest
  samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.windows.cs
  src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.windows.cs
Labels: pending documentation, approved

#2695 Return Camera Image (`Stream`) from `ICameraView.CaptureImage()`
  src/CommunityToolkit.Maui.Camera/Interfaces/ICameraView.shared.cs
  src/CommunityToolkit.Maui.Camera/Views/CameraView.shared.cs
Labels: approved, needs discussion, breaking change

#2769 Fix: .UseMauiCommunityToolkit() Analyzer when wrapped in preprocessor directives
  src/CommunityToolkit.Maui.Analyzers.UnitTests/UseCommunityToolkitCameraInitializationAnalyzerTests.cs
  src/CommunityToolkit.Maui.Analyzers.UnitTests/UseCommunityToolkitInitializationAnalyzerTests.cs
  src/CommunityToolkit.Maui.Analyzers.UnitTests/UseCommunityToolkitMediaElementInitializationAnalyzerTests.cs
  src/CommunityToolkit.Maui.Analyzers/UseCommunityToolkitInitializationAnalyzer.cs
  src/CommunityToolkit.Maui.Camera.Analyzers/UseCommunityToolkitCameraInitializationAnalyzer.cs
  src/CommunityToolkit.Maui.MediaElement.Analyzers/UseCommunityToolkitMediaElementInitializationAnalyzer.cs
Labels: approved
