Repository CommunityToolkit/Maui, pull requests merged in 2025-02, with the labels that each got.

#2413 Fix statusBar color changes on modal pages
  CONTRIBUTING.md
  src/CommunityToolkit.Maui.Core/AppBuilderExtensions.shared.cs
  src/CommunityToolkit.Maui.Core/Interfaces/IDialogFragmentService.android.cs
  src/CommunityToolkit.Maui.Core/Options.cs
  src/CommunityToolkit.Maui.Core/Services/DialogFragmentService.android.cs
  src/CommunityToolkit.Maui.Core/Services/DialogFragmentService.shared.cs
  src/CommunityToolkit.Maui.Core/Services/FragmentLifecycleManager.android.cs
  src/CommunityToolkit.Maui/AppBuilderExtensions.shared.cs
Labels: approved, documentation approved

#2491 Fix options not working for Core
  src/CommunityToolkit.Maui.Core/AppBuilderExtensions.shared.cs
  src/CommunityToolkit.Maui.Core/Services/DialogFragmentService.android.cs
  src/CommunityToolkit.Maui.UnitTests/BaseTest.cs
  src/CommunityToolkit.Maui.UnitTests/Extensions/AppBuilderExtensionsTests.cs
  src/CommunityToolkit.Maui/AppBuilderExtensions.shared.cs
Labels: area/core

#2304 Make it possible to define when the IconTintBehavior gets applied
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.macios.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs
  src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs
Labels: help wanted, stale

#1567 Expander CollectionView GridLayout 1557
  samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ExpanderViewModel.cs
  src/CommunityToolkit.Maui/Views/Expander/Expander.macios.cs
  src/CommunityToolkit.Maui/Views/Expander/Expander.shared.cs
  src/CommunityToolkit.Maui/Views/Expander/Expander.windows.cs
Labels: area/views

#2498 [Housekeeping] Improve Code Coverage Report
  .github/workflows/dotnet-build.yml
Labels: needs discussion

#2259 Fix Windows Media Element in MultiWindow Mode on exit Crash
  src/CommunityToolkit.Maui/Options.cs
Labels: 📽️ MediaElement

#2191 Rating view
  Directory.Build.props
  samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
  samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/RatingView/RatingViewCsharpPage.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/RatingView/RatingViewShowcasePage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/RatingView/RatingViewShowcasePage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/Pages/Views/RatingView/RatingViewXamlPage.xaml
  samples/CommunityToolkit.Maui.Sample/Pages/Views/RatingView/RatingViewXamlPage.xaml.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/RatingView/RatingViewShowcaseViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/RatingView/RatingViewViewModel.cs
  samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
  src/CommunityToolkit.Maui.Analyzers/AnalyzerReleases.Shipped.md
  src/CommunityToolkit.Maui.Analyzers/MaximumRatingRangeAnalyzer.cs
  src/CommunityToolkit.Maui.Analyzers/UseCommunityToolkitInitializationAnalyzer.cs
  src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
  src/CommunityToolkit.Maui.Core/Interfaces/IRatingView.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/Defaults/RatingViewDefaults.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/RatingChangedEventArgs.shared.cs
  src/CommunityToolkit.Maui.Core/Primitives/RatingViewFillOption.cs
  src/CommunityToolkit.Maui.Core/Primitives/RatingViewShapes.shared.cs
  src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
  src/CommunityToolkit.Maui.UnitTests/Views/RatingView/RatingViewTests.cs
  src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
  src/CommunityToolkit.Maui/Views/RatingView/RatingView.PathShapes.shared.cs
  src/CommunityToolkit.Maui/Views/RatingView/RatingView.shared.cs
Labels: approved, documentation approved, needs discussion

#2525 Increase `Microsoft.Maui.*` Dependencies to v9.0.40
  .github/workflows/dotnet-build.yml
  Directory.Build.props
  azure-pipelines.yml
  global.json
  src/CommunityToolkit.Maui.Camera/CommunityToolkit.Maui.Camera.csproj
  src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
Labels: needs discussion, requirements updated
